CONFIG_SPI=y
CONFIG_DISPLAY=y
CONFIG_SSD16XX=n
CONFIG_LOG=y
CONFIG_BT=y
CONFIG_BT_PERIPHERAL=y
CONFIG_BT_BROADCASTER=y
CONFIG_BT_DEVICE_NAME="Veea-the-tag"

# Required for manual driver
CONFIG_MIPI_DBI=y
CONFIG_MIPI_DBI_SPI=y
CONFIG_GPIO=y
CONFIG_HEAP_MEM_POOL_SIZE=4096
